// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';


const SUPABASE_URL = "https://chgjhesbvtqpzcnzauil.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNoZ2poZXNidnRxcHpjbnphdWlsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1NDc0MTEsImV4cCI6MjA3MjEyMzQxMX0.Uqsr1KhXS3OYMXqY7y-lY_TNJdC27Zq_8k3XWRiUM2k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});